# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.form_result import FormResult
from .raw_client import AsyncRawFormClient, RawFormClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FormClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFormClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFormClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFormClient
        """
        return self._raw_client

    def detect(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormResult:
        """
        Run cell detection on a PDF and return the detected `form_fields`
        along with a reusable `form_id`. No LLM matching, no fill, no
        clear — this is the OCR / layout step that `/form/fill` and
        `/form/clear` would otherwise run internally.

        The returned `form_id` references the uploaded PDF and its
        detected layout, and can be passed back to a subsequent
        `/form/fill`, `/form/clear`, or `/form/detect` call as the
        single input source — Pulse will skip detection on the fast
        path and reuse the cached cells.

        **Input modes** — provide exactly one of:
        - `form_id` — re-detect cells on a previously stored PDF.
          Useful when callers want to refresh layout after editing or
          when chaining detect calls.
        - `file_url` — public or pre-signed URL Pulse will download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `page_range` (alias `pages`, e.g. `"1-3,5"`) restricts
        the operation to a subset of pages.

        Synchronous by default — returns the detected layout inline.
        Set `async: true` to receive `{job_id, status: "pending"}`
        immediately and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **1 credit per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormResult
            Detected layout returned synchronously.

        Examples
        --------
        from pulse import Pulse

        client = Pulse(
            api_key="YOUR_API_KEY",
        )
        client.form.detect()
        """
        _response = self._raw_client.detect(
            file=file,
            file_url=file_url,
            form_id=form_id,
            page_range=page_range,
            async_=async_,
            request_options=request_options,
        )
        return _response.data

    def fill(
        self,
        *,
        instructions: str,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormResult:
        """
        Fill the fields of a PDF form with values inferred from a natural
        language `instructions` prompt. Works on both AcroForm PDFs
        (true form fields are written) and flat/scanned PDFs (values
        are rendered as an overlay using detected cells from OCR).

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call. Skips
          re-detection (fast path); the cached `form_fields` are
          reused.
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF. Pulse runs cell
          detection internally before filling.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `form_fields` lets callers supply or edit the detected
        cells before filling. Optional `page_range` (alias `pages`,
        e.g. `"1-3,5"`) restricts the operation to a subset of pages.

        Synchronous by default — returns the filled `FormResult` inline
        (including a `pdf_url` you can `GET` to download the PDF
        binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        instructions : str
            Required natural-language fill prompt.

        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormResult
            Filled `FormResult` returned synchronously.

        Examples
        --------
        from pulse import Pulse

        client = Pulse(
            api_key="YOUR_API_KEY",
        )
        client.form.fill(
            instructions="instructions",
        )
        """
        _response = self._raw_client.fill(
            instructions=instructions,
            file=file,
            file_url=file_url,
            form_id=form_id,
            form_fields=form_fields,
            page_range=page_range,
            async_=async_,
            request_options=request_options,
        )
        return _response.data

    def clear(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormResult:
        """
        Remove user-entered data from a PDF form, leaving the blank
        form template intact. Erases handwritten entries, typed values,
        and unchecks selected checkboxes — printed labels, field
        titles, section headers, and other static template content are
        preserved.

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call (fast
          path; cached layout reused).
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        `instructions` is optional. When omitted, Pulse clears every
        user-filled field deterministically (no LLM call) on AcroForm
        PDFs, eliminating any chance of hallucinated content. Provide
        a natural language prompt to clear only specific fields
        (e.g. `"clear only the address fields"`); targeted clears go
        through the LLM matcher with a delete-only filter.

        Optional `form_fields` and `page_range` (alias `pages`) behave
        the same as on [Form Fill](api:POST/form/fill).

        Synchronous by default — returns the cleared `FormResult`
        inline (including a `pdf_url` you can `GET` to download the
        PDF binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        instructions : typing.Optional[str]
            Optional natural language description of what to clear. When omitted, Pulse clears everything user-filled deterministically.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormResult
            Cleared `FormResult` returned synchronously.

        Examples
        --------
        from pulse import Pulse

        client = Pulse(
            api_key="YOUR_API_KEY",
        )
        client.form.clear()
        """
        _response = self._raw_client.clear(
            file=file,
            file_url=file_url,
            form_id=form_id,
            instructions=instructions,
            form_fields=form_fields,
            page_range=page_range,
            async_=async_,
            request_options=request_options,
        )
        return _response.data


class AsyncFormClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFormClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFormClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFormClient
        """
        return self._raw_client

    async def detect(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormResult:
        """
        Run cell detection on a PDF and return the detected `form_fields`
        along with a reusable `form_id`. No LLM matching, no fill, no
        clear — this is the OCR / layout step that `/form/fill` and
        `/form/clear` would otherwise run internally.

        The returned `form_id` references the uploaded PDF and its
        detected layout, and can be passed back to a subsequent
        `/form/fill`, `/form/clear`, or `/form/detect` call as the
        single input source — Pulse will skip detection on the fast
        path and reuse the cached cells.

        **Input modes** — provide exactly one of:
        - `form_id` — re-detect cells on a previously stored PDF.
          Useful when callers want to refresh layout after editing or
          when chaining detect calls.
        - `file_url` — public or pre-signed URL Pulse will download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `page_range` (alias `pages`, e.g. `"1-3,5"`) restricts
        the operation to a subset of pages.

        Synchronous by default — returns the detected layout inline.
        Set `async: true` to receive `{job_id, status: "pending"}`
        immediately and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **1 credit per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormResult
            Detected layout returned synchronously.

        Examples
        --------
        import asyncio

        from pulse import AsyncPulse

        client = AsyncPulse(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.form.detect()


        asyncio.run(main())
        """
        _response = await self._raw_client.detect(
            file=file,
            file_url=file_url,
            form_id=form_id,
            page_range=page_range,
            async_=async_,
            request_options=request_options,
        )
        return _response.data

    async def fill(
        self,
        *,
        instructions: str,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormResult:
        """
        Fill the fields of a PDF form with values inferred from a natural
        language `instructions` prompt. Works on both AcroForm PDFs
        (true form fields are written) and flat/scanned PDFs (values
        are rendered as an overlay using detected cells from OCR).

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call. Skips
          re-detection (fast path); the cached `form_fields` are
          reused.
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF. Pulse runs cell
          detection internally before filling.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `form_fields` lets callers supply or edit the detected
        cells before filling. Optional `page_range` (alias `pages`,
        e.g. `"1-3,5"`) restricts the operation to a subset of pages.

        Synchronous by default — returns the filled `FormResult` inline
        (including a `pdf_url` you can `GET` to download the PDF
        binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        instructions : str
            Required natural-language fill prompt.

        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormResult
            Filled `FormResult` returned synchronously.

        Examples
        --------
        import asyncio

        from pulse import AsyncPulse

        client = AsyncPulse(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.form.fill(
                instructions="instructions",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.fill(
            instructions=instructions,
            file=file,
            file_url=file_url,
            form_id=form_id,
            form_fields=form_fields,
            page_range=page_range,
            async_=async_,
            request_options=request_options,
        )
        return _response.data

    async def clear(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormResult:
        """
        Remove user-entered data from a PDF form, leaving the blank
        form template intact. Erases handwritten entries, typed values,
        and unchecks selected checkboxes — printed labels, field
        titles, section headers, and other static template content are
        preserved.

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call (fast
          path; cached layout reused).
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        `instructions` is optional. When omitted, Pulse clears every
        user-filled field deterministically (no LLM call) on AcroForm
        PDFs, eliminating any chance of hallucinated content. Provide
        a natural language prompt to clear only specific fields
        (e.g. `"clear only the address fields"`); targeted clears go
        through the LLM matcher with a delete-only filter.

        Optional `form_fields` and `page_range` (alias `pages`) behave
        the same as on [Form Fill](api:POST/form/fill).

        Synchronous by default — returns the cleared `FormResult`
        inline (including a `pdf_url` you can `GET` to download the
        PDF binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        instructions : typing.Optional[str]
            Optional natural language description of what to clear. When omitted, Pulse clears everything user-filled deterministically.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormResult
            Cleared `FormResult` returned synchronously.

        Examples
        --------
        import asyncio

        from pulse import AsyncPulse

        client = AsyncPulse(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.form.clear()


        asyncio.run(main())
        """
        _response = await self._raw_client.clear(
            file=file,
            file_url=file_url,
            form_id=form_id,
            instructions=instructions,
            form_fields=form_fields,
            page_range=page_range,
            async_=async_,
            request_options=request_options,
        )
        return _response.data
