# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from .. import core
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.form_result import FormResult
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFormClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def detect(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[FormResult]:
        """
        Run cell detection on a PDF and return the detected `form_fields`
        along with a reusable `form_id`. No LLM matching, no fill, no
        clear — this is the OCR / layout step that `/form/fill` and
        `/form/clear` would otherwise run internally.

        The returned `form_id` references the uploaded PDF and its
        detected layout, and can be passed back to a subsequent
        `/form/fill`, `/form/clear`, or `/form/detect` call as the
        single input source — Pulse will skip detection on the fast
        path and reuse the cached cells.

        **Input modes** — provide exactly one of:
        - `form_id` — re-detect cells on a previously stored PDF.
          Useful when callers want to refresh layout after editing or
          when chaining detect calls.
        - `file_url` — public or pre-signed URL Pulse will download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `page_range` (alias `pages`, e.g. `"1-3,5"`) restricts
        the operation to a subset of pages.

        Synchronous by default — returns the detected layout inline.
        Set `async: true` to receive `{job_id, status: "pending"}`
        immediately and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **1 credit per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[FormResult]
            Detected layout returned synchronously.
        """
        _response = self._client_wrapper.httpx_client.request(
            "form/detect",
            method="POST",
            data={
                "file_url": file_url,
                "form_id": form_id,
                "page_range": page_range,
                "async": async_,
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FormResult,
                    construct_type(
                        type_=FormResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def fill(
        self,
        *,
        instructions: str,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[FormResult]:
        """
        Fill the fields of a PDF form with values inferred from a natural
        language `instructions` prompt. Works on both AcroForm PDFs
        (true form fields are written) and flat/scanned PDFs (values
        are rendered as an overlay using detected cells from OCR).

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call. Skips
          re-detection (fast path); the cached `form_fields` are
          reused.
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF. Pulse runs cell
          detection internally before filling.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `form_fields` lets callers supply or edit the detected
        cells before filling. Optional `page_range` (alias `pages`,
        e.g. `"1-3,5"`) restricts the operation to a subset of pages.

        Synchronous by default — returns the filled `FormResult` inline
        (including a `pdf_url` you can `GET` to download the PDF
        binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        instructions : str
            Required natural-language fill prompt.

        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[FormResult]
            Filled `FormResult` returned synchronously.
        """
        _response = self._client_wrapper.httpx_client.request(
            "form/fill",
            method="POST",
            data={
                "file_url": file_url,
                "form_id": form_id,
                "instructions": instructions,
                "form_fields": form_fields,
                "page_range": page_range,
                "async": async_,
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FormResult,
                    construct_type(
                        type_=FormResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def clear(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[FormResult]:
        """
        Remove user-entered data from a PDF form, leaving the blank
        form template intact. Erases handwritten entries, typed values,
        and unchecks selected checkboxes — printed labels, field
        titles, section headers, and other static template content are
        preserved.

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call (fast
          path; cached layout reused).
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        `instructions` is optional. When omitted, Pulse clears every
        user-filled field deterministically (no LLM call) on AcroForm
        PDFs, eliminating any chance of hallucinated content. Provide
        a natural language prompt to clear only specific fields
        (e.g. `"clear only the address fields"`); targeted clears go
        through the LLM matcher with a delete-only filter.

        Optional `form_fields` and `page_range` (alias `pages`) behave
        the same as on [Form Fill](api:POST/form/fill).

        Synchronous by default — returns the cleared `FormResult`
        inline (including a `pdf_url` you can `GET` to download the
        PDF binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        instructions : typing.Optional[str]
            Optional natural language description of what to clear. When omitted, Pulse clears everything user-filled deterministically.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[FormResult]
            Cleared `FormResult` returned synchronously.
        """
        _response = self._client_wrapper.httpx_client.request(
            "form/clear",
            method="POST",
            data={
                "file_url": file_url,
                "form_id": form_id,
                "instructions": instructions,
                "form_fields": form_fields,
                "page_range": page_range,
                "async": async_,
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FormResult,
                    construct_type(
                        type_=FormResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFormClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def detect(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[FormResult]:
        """
        Run cell detection on a PDF and return the detected `form_fields`
        along with a reusable `form_id`. No LLM matching, no fill, no
        clear — this is the OCR / layout step that `/form/fill` and
        `/form/clear` would otherwise run internally.

        The returned `form_id` references the uploaded PDF and its
        detected layout, and can be passed back to a subsequent
        `/form/fill`, `/form/clear`, or `/form/detect` call as the
        single input source — Pulse will skip detection on the fast
        path and reuse the cached cells.

        **Input modes** — provide exactly one of:
        - `form_id` — re-detect cells on a previously stored PDF.
          Useful when callers want to refresh layout after editing or
          when chaining detect calls.
        - `file_url` — public or pre-signed URL Pulse will download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `page_range` (alias `pages`, e.g. `"1-3,5"`) restricts
        the operation to a subset of pages.

        Synchronous by default — returns the detected layout inline.
        Set `async: true` to receive `{job_id, status: "pending"}`
        immediately and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **1 credit per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[FormResult]
            Detected layout returned synchronously.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "form/detect",
            method="POST",
            data={
                "file_url": file_url,
                "form_id": form_id,
                "page_range": page_range,
                "async": async_,
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FormResult,
                    construct_type(
                        type_=FormResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def fill(
        self,
        *,
        instructions: str,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[FormResult]:
        """
        Fill the fields of a PDF form with values inferred from a natural
        language `instructions` prompt. Works on both AcroForm PDFs
        (true form fields are written) and flat/scanned PDFs (values
        are rendered as an overlay using detected cells from OCR).

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call. Skips
          re-detection (fast path); the cached `form_fields` are
          reused.
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF. Pulse runs cell
          detection internally before filling.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        Optional `form_fields` lets callers supply or edit the detected
        cells before filling. Optional `page_range` (alias `pages`,
        e.g. `"1-3,5"`) restricts the operation to a subset of pages.

        Synchronous by default — returns the filled `FormResult` inline
        (including a `pdf_url` you can `GET` to download the PDF
        binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        instructions : str
            Required natural-language fill prompt.

        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[FormResult]
            Filled `FormResult` returned synchronously.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "form/fill",
            method="POST",
            data={
                "file_url": file_url,
                "form_id": form_id,
                "instructions": instructions,
                "form_fields": form_fields,
                "page_range": page_range,
                "async": async_,
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FormResult,
                    construct_type(
                        type_=FormResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def clear(
        self,
        *,
        file: typing.Optional[core.File] = OMIT,
        file_url: typing.Optional[str] = OMIT,
        form_id: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        form_fields: typing.Optional[str] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        async_: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[FormResult]:
        """
        Remove user-entered data from a PDF form, leaving the blank
        form template intact. Erases handwritten entries, typed values,
        and unchecks selected checkboxes — printed labels, field
        titles, section headers, and other static template content are
        preserved.

        **Input modes** — provide exactly one of:
        - `form_id` — reuse a previously processed form from a prior
          `/form/detect`, `/form/fill`, or `/form/clear` call (fast
          path; cached layout reused).
        - `file_url` — public or pre-signed URL of a PDF Pulse will
          download.
        - `file` — direct binary upload of the PDF.

        All three input modes ride on the same `multipart/form-data`
        request body. (Callers sending `Content-Type: application/json`
        with `form_id` / `file_url` are still accepted server-side for
        backward compatibility, but the SDKs only model the multipart
        form.)

        `instructions` is optional. When omitted, Pulse clears every
        user-filled field deterministically (no LLM call) on AcroForm
        PDFs, eliminating any chance of hallucinated content. Provide
        a natural language prompt to clear only specific fields
        (e.g. `"clear only the address fields"`); targeted clears go
        through the LLM matcher with a delete-only filter.

        Optional `form_fields` and `page_range` (alias `pages`) behave
        the same as on [Form Fill](api:POST/form/fill).

        Synchronous by default — returns the cleared `FormResult`
        inline (including a `pdf_url` you can `GET` to download the
        PDF binary). Set `async: true` to receive `{job_id, status:
        "pending"}` and poll [GET /job/{jobId}](api:GET/job/{jobId}).

        Billed at **3 credits per page**. Requires the `form_filler`
        feature flag to be enabled for your organization.

        Parameters
        ----------
        file : typing.Optional[core.File]
            See core.File for more documentation

        file_url : typing.Optional[str]
            Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`.

        form_id : typing.Optional[str]
            Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.

        instructions : typing.Optional[str]
            Optional natural language description of what to clear. When omitted, Pulse clears everything user-filled deterministically.

        form_fields : typing.Optional[str]
            Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string.

        page_range : typing.Optional[str]
            Restrict the operation to a subset of pages, e.g. `"1-3,5"`.

        async_ : typing.Optional[str]
            Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[FormResult]
            Cleared `FormResult` returned synchronously.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "form/clear",
            method="POST",
            data={
                "file_url": file_url,
                "form_id": form_id,
                "instructions": instructions,
                "form_fields": form_fields,
                "page_range": page_range,
                "async": async_,
            },
            files={
                **({"file": file} if file is not None else {}),
            },
            request_options=request_options,
            omit=OMIT,
            force_multipart=True,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    FormResult,
                    construct_type(
                        type_=FormResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
