# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .async_submission_response_status import AsyncSubmissionResponseStatus


class AsyncSubmissionResponse(UncheckedBaseModel):
    """
    Acknowledgement returned when a request is submitted for asynchronous processing. Poll `GET /job/{job_id}` to check status and retrieve results.
    """

    job_id: str = pydantic.Field()
    """
    Identifier assigned to the asynchronous job.
    """

    status: AsyncSubmissionResponseStatus = pydantic.Field()
    """
    Initial status reported by the server.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable description of the accepted job.
    """

    queued_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="queuedAt")] = (
        pydantic.Field(default=None)
    )
    """
    **Deprecated** — Timestamp indicating when the job was accepted. Retained for backward compatibility. Use `GET /job/{jobId}` for timing details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
