# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class BatchExtractionIds(UncheckedBaseModel):
    """
    Identifies extractions for batch processing.
    Provide exactly one of `batch_extract_id` or `extraction_ids`.
    """

    batch_extract_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a prior `/batch/extract` run. All completed child extraction IDs will be used.
    """

    extraction_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Explicit list of extraction IDs to process.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
