# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class BatchInputSource(UncheckedBaseModel):
    """
    Input source for batch file enumeration. Provide exactly one of
    `s3_prefix`, `local_path`, or `file_urls`.
    """

    s_3_prefix: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="s3_prefix")] = pydantic.Field(
        default=None
    )
    """
    S3 URI prefix (e.g. `s3://bucket/folder/`). All supported files under this prefix will be processed.
    """

    local_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Absolute path to a local directory. All supported files in the directory will be processed.
    """

    file_urls: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Explicit list of file URLs to download and process.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
