# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .batch_file_upload import BatchFileUpload


class BatchInputSource(UncheckedBaseModel):
    """
    Input source for batch file enumeration. Provide exactly one of
    `s3_prefix`, `file_urls`, or `files`.
    """

    s_3_prefix: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="s3_prefix"),
        pydantic.Field(
            alias="s3_prefix",
            description="S3 URI prefix (e.g. `s3://bucket/folder/`). All supported files under this prefix will be processed.",
        ),
    ] = None
    file_urls: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Explicit list of file URLs to download and process.
    """

    files: typing.Optional[typing.List[BatchFileUpload]] = pydantic.Field(default=None)
    """
    Inline file uploads. Each entry contains a filename and base64-encoded file content. Use this when the client has local files that need to be sent to a remote API server.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
