# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class BatchOutputDestination(UncheckedBaseModel):
    """
    Output destination for batch results. Provide at least one of
    `s3_prefix` or `local_path`. Both may be specified to save to
    multiple locations.
    """

    s_3_prefix: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="s3_prefix")] = pydantic.Field(
        default=None
    )
    """
    S3 URI prefix where result JSON files will be written.
    """

    local_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Absolute path to a local directory for result JSON files.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
