# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .batch_tables_response_status import BatchTablesResponseStatus


class BatchTablesResponse(UncheckedBaseModel):
    """
    Acknowledgement returned when batch tables is started.
    """

    batch_job_id: str = pydantic.Field()
    """
    Identifier for the batch job. Poll `GET /job/{batch_job_id}` for progress and results.
    """

    status: BatchTablesResponseStatus
    total_extractions: int = pydantic.Field()
    """
    Number of extractions to process.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
