# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .bounding_box_image_classification import BoundingBoxImageClassification
from .visual_type import VisualType


class BoundingBoxImage(UncheckedBaseModel):
    """
    Detected or embedded visual (chart or image) returned under `bounding_boxes.Images`. For PDFs/images, populated when figure detection is enabled. For spreadsheets, populated for embedded charts and images. `image_url` is set when `figure_processing.show_images` is enabled.
    """

    id: str = pydantic.Field()
    """
    Stable visual identifier (e.g. `excel_image_1_1`, `fig-3`). Use this to join with the `data-bb-image-id` attribute in the markdown output.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short caption for the visual (e.g. `Chart: Revenue`). Populated by the spreadsheet parser; PDF figures may leave this empty when no caption is detected.
    """

    visual_type: VisualType = pydantic.Field()
    """
    Visual class. Drives whether `figure_processing.description` / `figure_processing.show_images` apply to this entry.
    """

    page_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    1-indexed page or sheet index.
    """

    bounding_box: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Document coordinate polygon when available. Spreadsheet visuals typically use an empty array and rely on `excel_range` for positioning.
    """

    image_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pulse-hosted URL for the visual image bytes. Present when `figure_processing.show_images` was enabled for this visual_type. Spreadsheet visuals proxy through `GET /results/{jobId}/images/{filename}`; inline figure flows may use a data URI.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generated visual description. Present when `figure_processing.description` was enabled for this visual_type.
    """

    classification: typing.Optional[BoundingBoxImageClassification] = pydantic.Field(default=None)
    """
    Visual classification metadata when classification was run. Includes confidence, model name, and any non-fatal classification error.
    """

    sheet_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spreadsheet-only sheet name.
    """

    sheet_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Spreadsheet-only parsed sheet index after hidden-sheet filtering.
    """

    workbook_sheet_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Spreadsheet-only original workbook sheet index.
    """

    excel_range: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spreadsheet-only anchor or covered cell range for the visual.
    """

    chart_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spreadsheet chart class name (e.g. `BarChart`, `LineChart`) when `visual_type` is `chart`.
    """

    chart_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spreadsheet chart title when available.
    """

    source_ranges: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Spreadsheet chart source ranges when available, e.g. `["Charts!$B$1:$B$3"]`.
    """

    render_error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional non-fatal rendering error for spreadsheet visuals. When set, the visual entry is still returned but `image_url` may be omitted.
    """

    description_error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional non-fatal description-generation error.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
