# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class BoundingBoxItem(UncheckedBaseModel):
    """
    Common base shape used for `Text`, `Title`, and `Footer` bounding-box entries. Spreadsheet rows may carry additional sheet-scoped fields such as `excel_range` and `sheet_name`; forward-compatible extra properties are accepted.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable bounding-box identifier (e.g. `txt-1`, `excel_title_0`). Used by extensions like `footnoteReferences` to cross-reference paragraphs.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Plain-text content of the region.
    """

    page_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    1-indexed page number. For spreadsheets this matches the parsed sheet index after hidden-sheet filtering.
    """

    bounding_box: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Document coordinate polygon when available. Spreadsheet visuals may use an empty array and `excel_range` instead.
    """

    excel_range: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spreadsheet-only anchor or covered cell range.
    """

    sheet_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spreadsheet-only sheet name.
    """

    sheet_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Spreadsheet-only parsed sheet index after hidden-sheet filtering.
    """

    workbook_sheet_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Spreadsheet-only original workbook sheet index.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
