# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .bounding_box_image import BoundingBoxImage
from .bounding_box_item import BoundingBoxItem
from .bounding_box_table import BoundingBoxTable


class BoundingBoxes(UncheckedBaseModel):
    """
    Positional bounding-box data for text, titles, headers, footers, images, and tables. Used by the frontend for annotation overlays and by SDK consumers to access detected visuals (charts and images) returned under `Images`. Keys not listed here are accepted for forward compatibility (e.g. `markdown_with_ids`, `defined_names`).
    """

    images: typing_extensions.Annotated[
        typing.Optional[typing.List[BoundingBoxImage]],
        FieldMetadata(alias="Images"),
        pydantic.Field(
            alias="Images",
            description="Detected or embedded visuals. `image_url` is populated when `figure_processing.show_images` was enabled and the entry's `visual_type` matched the requested target.",
        ),
    ] = None
    tables: typing_extensions.Annotated[
        typing.Optional[typing.List[BoundingBoxTable]],
        FieldMetadata(alias="Tables"),
        pydantic.Field(
            alias="Tables",
            description="Detected tables. Each entry carries a `table_info` block plus optional `cell_data`.",
        ),
    ] = None
    text: typing_extensions.Annotated[
        typing.Optional[typing.List[BoundingBoxItem]],
        FieldMetadata(alias="Text"),
        pydantic.Field(
            alias="Text",
            description="Body-text paragraphs and detected text regions. For spreadsheets, includes free-form text outside table regions (titles, captions, instructions).",
        ),
    ] = None
    title: typing_extensions.Annotated[
        typing.Optional[typing.List[BoundingBoxItem]],
        FieldMetadata(alias="Title"),
        pydantic.Field(
            alias="Title",
            description="Detected title regions. Spreadsheets emit one `Sheet: <name>` title per processed sheet.",
        ),
    ] = None
    footer: typing_extensions.Annotated[
        typing.Optional[typing.List[BoundingBoxItem]],
        FieldMetadata(alias="Footer"),
        pydantic.Field(
            alias="Footer", description='Detected footer regions (e.g. spreadsheet "Totals" rows, PDF page footers).'
        ),
    ] = None
    markdown_with_ids: typing.Optional[str] = pydantic.Field(default=None)
    """
    Markdown variant with stable `data-bb-*-id` attributes in figure / table / text tags. Lets clients join rendered HTML back to bounding-box entries by id.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
