# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .bounding_box_table_table_info import BoundingBoxTableTableInfo


class BoundingBoxTable(UncheckedBaseModel):
    """
    Detected table region returned under `bounding_boxes.Tables`. Carries a structured `table_info` block plus optional `cell_data`. Kept loose with `additionalProperties: true` to round-trip future fields the server may add (e.g. layout metadata).
    """

    table_info: typing.Optional[BoundingBoxTableTableInfo] = None
    cell_data: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Table cell payload when available. Shape varies by extraction path; SDK consumers should treat as opaque.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
