# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DocumentMetadataStructure(UncheckedBaseModel):
    """
    Deterministic structure derived from the source document format.
    """

    page_count: typing.Optional[int] = pydantic.Field(default=None)
    page_labels: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    page_sizes: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    outline_count: typing.Optional[int] = pydantic.Field(default=None)
    attachment_count: typing.Optional[int] = pydantic.Field(default=None)
    annotation_count: typing.Optional[int] = pydantic.Field(default=None)
    form_field_count: typing.Optional[int] = pydantic.Field(default=None)
    sheet_count: typing.Optional[int] = pydantic.Field(default=None)
    sheet_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    sheet_visibility: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    slide_count: typing.Optional[int] = pydantic.Field(default=None)
    width_px: typing.Optional[int] = pydantic.Field(default=None)
    height_px: typing.Optional[int] = pydantic.Field(default=None)
    frame_count: typing.Optional[int] = pydantic.Field(default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
