# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DocumentMetadataProperties(UncheckedBaseModel):
    """
    Normalized native document properties. Absent properties are omitted.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    authors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    subject: typing.Optional[str] = pydantic.Field(default=None)
    description: typing.Optional[str] = pydantic.Field(default=None)
    keywords: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    language: typing.Optional[str] = pydantic.Field(default=None)
    application: typing.Optional[str] = pydantic.Field(default=None)
    application_version: typing.Optional[str] = pydantic.Field(default=None)
    producer: typing.Optional[str] = pydantic.Field(default=None)
    last_modified_by: typing.Optional[str] = pydantic.Field(default=None)
    revision: typing.Optional[str] = pydantic.Field(default=None)
    category: typing.Optional[str] = pydantic.Field(default=None)
    content_status: typing.Optional[str] = pydantic.Field(default=None)
    identifier: typing.Optional[str] = pydantic.Field(default=None)
    version: typing.Optional[str] = pydantic.Field(default=None)
    company: typing.Optional[str] = pydantic.Field(default=None)
    manager: typing.Optional[str] = pydantic.Field(default=None)
    template: typing.Optional[str] = pydantic.Field(default=None)
    presentation_format: typing.Optional[str] = pydantic.Field(default=None)
    editing_time_minutes: typing.Optional[int] = pydantic.Field(default=None)
    copyright: typing.Optional[str] = pydantic.Field(default=None)
    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 8601 timestamp when the source provides one.
    """

    modified_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 8601 timestamp when the source provides one.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
