# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DocumentMetadataFile(UncheckedBaseModel):
    """
    Transport-level facts derived from the uploaded source file.
    """

    name: str
    extension: str
    media_type: str
    size_bytes: int
    sha256: typing.Optional[str] = pydantic.Field(default=None)
    """
    SHA-256 content digest, when hashing is available.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
