# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .bounding_boxes import BoundingBoxes
from .extract_response_chunks import ExtractResponseChunks
from .extract_response_extensions import ExtractResponseExtensions
from .plan_info import PlanInfo
from .structured_output_result import StructuredOutputResult


class ExtractResponse(UncheckedBaseModel):
    """
    Full extraction result returned by the synchronous `/extract` endpoint. Inherits all core fields and adds deprecated backward-compatibility fields.
    """

    markdown: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary markdown content extracted from the document. Always present in the new format.
    """

    extensions: typing.Optional[ExtractResponseExtensions] = pydantic.Field(default=None)
    """
    Output from enabled extensions. Each key corresponds to an extension that was enabled in the request under `extensions.*`. Only keys for enabled extensions are present.
    """

    bounding_boxes: typing.Optional[BoundingBoxes] = pydantic.Field(default=None)
    """
    Positional bounding-box data for text, titles, headers, footers, images, and tables. `Images` carries chart/image visuals (with `image_url` when `figure_processing.show_images` is enabled), `Tables` the detected tables, and `Text`/`Title`/`Footer` the paragraph/title/footer regions. Additional keys (e.g. `markdown_with_ids`, `defined_names`) round-trip without being typed.
    """

    extraction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Persisted extraction ID. Present when storage is enabled (default). Use this ID with `/split` and `/schema` endpoints.
    """

    extraction_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to view the extraction on the Pulse platform. Present when storage is enabled.
    """

    page_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of pages processed.
    """

    plan_info: typing.Optional[PlanInfo] = pydantic.Field(default=None)
    """
    Billing tier and cumulative usage information. Includes `total_credits_used` (primary billing metric) and `pages_used` (legacy compatibility).
    """

    warnings: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Non-fatal warnings generated during extraction. Includes deprecation notices when legacy input parameters are used, as well as processing warnings (e.g. word-level bounding box limitations).
    """

    credits_used: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of credits consumed by this request. Only present when the organization has the credit billing system enabled.
    """

    html: typing.Optional[str] = pydantic.Field(default=None)
    """
    **Deprecated** — Use `extensions.altOutputs.html` instead. HTML representation of the extracted content. Present when the legacy `returnHtml` input was used.
    """

    chunks: typing.Optional[ExtractResponseChunks] = pydantic.Field(default=None)
    """
    **Deprecated** — Use `extensions.chunking` instead. Document content split into chunks. Present when the legacy `chunking` input was used.
    """

    structured_output: typing.Optional[StructuredOutputResult] = pydantic.Field(default=None)
    """
    **Deprecated** — Only present when the deprecated `structuredOutput` input parameter was used. Use the `/schema` endpoint after extraction instead.
    """

    input_schema: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    **Deprecated** — Echo of the schema that was applied. Only present when the deprecated `structuredOutput` input parameter was used.
    """

    schema_error: typing.Optional[str] = pydantic.Field(default=None)
    """
    **Deprecated** — Error message if schema processing failed via the deprecated `structuredOutput` input parameter.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    **Deprecated** — Alias for `markdown`. Included for backward compatibility with older SDK versions. Prefer `markdown`.
    """

    job_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    **Deprecated** — Identifier assigned to the extraction job. Retained for backward compatibility.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    **Deprecated** — Additional metadata supplied by the backend. Retained for backward compatibility.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
