# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractAsyncRequestSpreadsheet(UncheckedBaseModel):
    """
    Settings for Excel/spreadsheet extraction. Controls handling of hidden rows, columns, and sheets. Only applies to `.xlsx` and `.xls` files. Accepts both camelCase and snake_case field names.
    """

    include_hidden_rows: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="includeHiddenRows"),
        pydantic.Field(alias="includeHiddenRows", description="Include rows that are hidden in the Excel workbook."),
    ] = None
    include_hidden_cols: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="includeHiddenCols"),
        pydantic.Field(alias="includeHiddenCols", description="Include columns that are hidden in the Excel workbook."),
    ] = None
    include_hidden_sheets: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="includeHiddenSheets"),
        pydantic.Field(
            alias="includeHiddenSheets", description="Include sheets that are hidden in the Excel workbook."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
