# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractResponsePlanInfo(UncheckedBaseModel):
    """
    Billing tier and usage information.
    """

    tier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current plan tier name.
    """

    pages_used: typing.Optional[int] = pydantic.Field(default=None)
    """
    Cumulative pages used after this extraction.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable plan note.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
