# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_async_request_extensions_alt_outputs import ExtractAsyncRequestExtensionsAltOutputs
from .extract_async_request_extensions_chunking import ExtractAsyncRequestExtensionsChunking


class ExtractAsyncRequestExtensions(UncheckedBaseModel):
    """
    Settings that enable additional processing passes or alternate output formats. Each enabled extension produces a corresponding output field under `response.extensions.*`.
    """

    footnote_references: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="footnoteReferences"),
        pydantic.Field(
            alias="footnoteReferences", description="Link footnote markers to their corresponding footnote text."
        ),
    ] = None
    document_metadata: typing.Optional[bool] = pydantic.Field(
        default=None,
        description="Extract the maximum safely recoverable metadata from the original file bytes. Results appear under `response.extensions.document_metadata`.",
    )
    chunking: typing.Optional[ExtractAsyncRequestExtensionsChunking] = pydantic.Field(default=None)
    """
    Chunking configuration. When provided, the document is split into chunks using the specified strategies. Results appear in `response.extensions.chunking`.
    """

    alt_outputs: typing_extensions.Annotated[
        typing.Optional[ExtractAsyncRequestExtensionsAltOutputs],
        FieldMetadata(alias="altOutputs"),
        pydantic.Field(
            alias="altOutputs",
            description="Alternate output format options. Each enabled format produces a corresponding field under `response.extensions.altOutputs`.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
