# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_response_extensions_alt_outputs import ExtractResponseExtensionsAltOutputs
from .extract_response_extensions_chunking import ExtractResponseExtensionsChunking


class ExtractResponseExtensions(UncheckedBaseModel):
    """
    Output from enabled extensions. Each key corresponds to an extension that was enabled in the request under `extensions.*`. Only keys for enabled extensions are present.
    """

    chunking: typing.Optional[ExtractResponseExtensionsChunking] = pydantic.Field(default=None)
    """
    Chunk results by strategy. Present when `extensions.chunking` was provided in the request.
    """

    merge_tables: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]], FieldMetadata(alias="mergeTables")
    ] = pydantic.Field(default=None)
    """
    Merge tables result/metadata. Present when `extensions.mergeTables` was enabled.
    """

    footnote_references: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]], FieldMetadata(alias="footnoteReferences")
    ] = pydantic.Field(default=None)
    """
    Footnote linking result/metadata. Present when `extensions.footnoteReferences` was enabled.
    """

    alt_outputs: typing_extensions.Annotated[
        typing.Optional[ExtractResponseExtensionsAltOutputs], FieldMetadata(alias="altOutputs")
    ] = pydantic.Field(default=None)
    """
    Alternate output formats. Each key corresponds to an enabled alt output.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
