# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_response_extensions_alt_outputs_wlbb_words_item import ExtractResponseExtensionsAltOutputsWlbbWordsItem


class ExtractResponseExtensionsAltOutputsWlbb(UncheckedBaseModel):
    """
    Word-level bounding box data. Present when `extensions.altOutputs.wlbb` was enabled and input is a PDF.
    """

    words: typing.Optional[typing.List[ExtractResponseExtensionsAltOutputsWlbbWordsItem]] = pydantic.Field(default=None)
    """
    List of detected words with their positions.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if word-level extraction failed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
