# This file was auto-generated by Fern from our API Definition.

import typing

ExtractOptionsExtensionsChunkingChunkTypesItem = typing.Union[
    typing.Literal["semantic", "header", "page", "recursive"], typing.Any
]
