# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_options_extensions_alt_outputs import ExtractOptionsExtensionsAltOutputs
from .extract_options_extensions_chunking import ExtractOptionsExtensionsChunking


class ExtractOptionsExtensions(UncheckedBaseModel):
    """
    Settings that enable additional processing passes or alternate output formats. Each enabled extension produces a corresponding output field under `response.extensions.*`.
    """

    merge_tables: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="mergeTables")] = (
        pydantic.Field(default=None)
    )
    """
    Merge tables that span multiple pages into a single table.
    """

    footnote_references: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="footnoteReferences")
    ] = pydantic.Field(default=None)
    """
    Link footnote markers to their corresponding footnote text.
    """

    chunking: typing.Optional[ExtractOptionsExtensionsChunking] = pydantic.Field(default=None)
    """
    Chunking configuration. When provided, the document is split into chunks using the specified strategies. Results appear in `response.extensions.chunking`.
    """

    alt_outputs: typing_extensions.Annotated[
        typing.Optional[ExtractOptionsExtensionsAltOutputs], FieldMetadata(alias="altOutputs")
    ] = pydantic.Field(default=None)
    """
    Alternate output format options. Each enabled format produces a corresponding field under `response.extensions.altOutputs`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
