# This file was auto-generated by Fern from our API Definition.

from .async_submission_response import AsyncSubmissionResponse

ExtractAsyncSubmissionResponse = AsyncSubmissionResponse
"""
**Deprecated** — Use `AsyncSubmissionResponse` instead. This alias is retained so that existing SDK imports continue to work.
"""
