# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractInputFigureProcessing(UncheckedBaseModel):
    """
    Settings that control how figures and embedded visuals are processed. Applies to both PDFs/images (where figures are detected from layout) and spreadsheets (where charts and embedded images are read directly from the workbook). These options affect the markdown output and the `bounding_boxes.Images[]` array; they do not produce additional output fields elsewhere in the response.
    """

    description: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Generate descriptive captions for extracted visuals. When `true`, applies to both detected charts and non-chart images. Captions appear under `bounding_boxes.Images[].description` and inline in the markdown output where applicable.
    """

    show_images: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="showImages"),
        pydantic.Field(
            alias="showImages",
            description="Return image URLs for extracted visuals. When `true`, applies to both charts and non-chart images. URLs are emitted under `bounding_boxes.Images[].image_url` — typically a Pulse-hosted proxy URL served from `GET /results/{jobId}/images/{filename}`. Spreadsheet charts and embedded images are read directly from the workbook; PDF/image inputs use detected figure regions.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
