# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractAsyncRequestExtensionsAltOutputs(UncheckedBaseModel):
    """
    Alternate output format options. Each enabled format produces a corresponding field under `response.extensions.altOutputs`.
    """

    wlbb: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable word-level bounding boxes. Runs an additional OCR model to derive bounding boxes for each word. Only applies to PDFs. Results in `response.extensions.altOutputs.wlbb`.
    """

    return_html: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="returnHtml")] = pydantic.Field(
        default=None
    )
    """
    Include an HTML representation of the document. When enabled, `response.markdown` is still present and the HTML is available at `response.extensions.altOutputs.html`.
    """

    return_xml: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="returnXml")] = pydantic.Field(
        default=None
    )
    """
    Include an XML representation of the document. Results in `response.extensions.altOutputs.xml`. (Work in progress.)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
