# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_response_extensions_alt_outputs_wlbb import ExtractResponseExtensionsAltOutputsWlbb


class ExtractResponseExtensionsAltOutputs(UncheckedBaseModel):
    """
    Alternate output formats. Each key corresponds to an enabled alt output.
    """

    wlbb: typing.Optional[ExtractResponseExtensionsAltOutputsWlbb] = pydantic.Field(default=None)
    """
    Word-level bounding box data. Present when `extensions.altOutputs.wlbb` was enabled and input is a PDF.
    """

    html: typing.Optional[str] = pydantic.Field(default=None)
    """
    HTML representation of the document. Present when `extensions.altOutputs.returnHtml` was enabled.
    """

    xml: typing.Optional[str] = pydantic.Field(default=None)
    """
    XML representation of the document. Present when `extensions.altOutputs.returnXml` was enabled. (WIP)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
