# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractResponseChunks(UncheckedBaseModel):
    """
    Document content split into chunks using the requested strategies. Only present when `chunking` was specified in the request.
    """

    semantic: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Semantically-segmented chunks.
    """

    header: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Chunks split by document headers/headings.
    """

    page: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    One chunk per page.
    """

    recursive: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Recursively-split chunks respecting size limits.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
