# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractResponseExtensionsAltOutputsWlbbWordsItem(UncheckedBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the word (e.g. "w-1", "w-2", …).
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    The recognised word text.
    """

    page_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    1-indexed page number in the original document.
    """

    bounding_box: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Flat 4-corner polygon: [x1,y1, x2,y2, x3,y3, x4,y4]. All coordinates normalised to 0–1 range.
    """

    average_word_confidence: typing.Optional[float] = pydantic.Field(default=None)
    """
    Recognition confidence score (0–1).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
