# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_input_extensions import ExtractInputExtensions
from .extract_input_figure_processing import ExtractInputFigureProcessing
from .extract_input_model import ExtractInputModel
from .extract_input_schema import ExtractInputSchema
from .extract_input_spreadsheet import ExtractInputSpreadsheet
from .extract_input_storage import ExtractInputStorage
from .extract_input_structured_output import ExtractInputStructuredOutput


class ExtractInput(UncheckedBaseModel):
    """
    Input schema for extraction requests. Provide either file (direct upload) or fileUrl (remote URL).
    """

    file: typing.Optional[bytes] = pydantic.Field(default=None)
    """
    Document to upload directly. Required unless fileUrl is provided.
    """

    file_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fileUrl"),
        pydantic.Field(
            alias="fileUrl",
            description="Public or pre-signed URL that Pulse will download and extract. Required unless file is provided.",
        ),
    ] = None
    model: typing.Optional[ExtractInputModel] = pydantic.Field(default=None)
    """
    Extraction model to use. When set to `pulse-ultra-2`, routes the request through Pulse Ultra 2 (self-hosted VPC model) instead of the default cloud-based service. If omitted or set to `default`, the default model is used.
    """

    extraction_config_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="extractionConfigId"),
        pydantic.Field(
            alias="extractionConfigId",
            description='UUID of a saved extraction configuration (a "preset"). When provided, the server loads the saved configuration and applies its options on top of any inline parameters supplied in this request. Inline parameters always take precedence over preset values for the same field. Saved configs are managed via the platform UI or the `input_extractions` admin endpoints.',
        ),
    ] = None
    pages: typing.Optional[str] = pydantic.Field(default=None)
    """
    Page range filter supporting segments such as `1-2` or mixed ranges like `1-2,5`.
    """

    figure_processing: typing_extensions.Annotated[
        typing.Optional[ExtractInputFigureProcessing],
        FieldMetadata(alias="figureProcessing"),
        pydantic.Field(
            alias="figureProcessing",
            description="Settings that control how figures and embedded visuals are processed. Applies to both PDFs/images (where figures are detected from layout) and spreadsheets (where charts and embedded images are read directly from the workbook). These options affect the markdown output and the `bounding_boxes.Images[]` array; they do not produce additional output fields elsewhere in the response.",
        ),
    ] = None
    extensions: typing.Optional[ExtractInputExtensions] = pydantic.Field(default=None)
    """
    Settings that enable additional processing passes or alternate output formats. Each enabled extension produces a corresponding output field under `response.extensions.*`.
    """

    spreadsheet: typing.Optional[ExtractInputSpreadsheet] = pydantic.Field(default=None)
    """
    Settings for Excel/spreadsheet extraction. Controls handling of hidden rows, columns, and sheets, and whether numeric cells are rendered using their display format or underlying raw value. Applies to `.xlsx`, `.xlsm`, and `.xls` files. Accepts both camelCase and snake_case field names.
    """

    storage: typing.Optional[ExtractInputStorage] = pydantic.Field(default=None)
    """
    Options for persisting extraction artifacts. When enabled (default), artifacts are saved to storage and a database record is created.
    """

    async_: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="async"),
        pydantic.Field(
            alias="async",
            description="If true, returns immediately with a job_id for polling via GET /job/{jobId}. Otherwise processes synchronously.",
        ),
    ] = None
    structured_output: typing_extensions.Annotated[
        typing.Optional[ExtractInputStructuredOutput],
        FieldMetadata(alias="structuredOutput"),
        pydantic.Field(
            alias="structuredOutput",
            description="**⚠️ DEPRECATED** — Use the `/schema` endpoint after extraction instead. Pass the `extraction_id` from the extract response to `/schema` with your `schema_config`. This parameter still works for backward compatibility but will be removed in a future version.",
        ),
    ] = None
    schema_: typing_extensions.Annotated[
        typing.Optional[ExtractInputSchema],
        FieldMetadata(alias="schema"),
        pydantic.Field(
            alias="schema",
            description="(Deprecated) JSON schema describing structured data to extract. Use structuredOutput instead. Accepts either a JSON object or a stringified JSON representation.",
        ),
    ] = None
    schema_prompt: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="schemaPrompt"),
        pydantic.Field(
            alias="schemaPrompt",
            description="(Deprecated) Natural language prompt for schema-guided extraction. Use structuredOutput.schemaPrompt instead.",
        ),
    ] = None
    custom_prompt: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="customPrompt"),
        pydantic.Field(
            alias="customPrompt",
            description="(Deprecated) Custom instructions that augment the default extraction behaviour. Use `figureProcessing` or `extensions` instead.",
        ),
    ] = None
    chunking: typing.Optional[str] = pydantic.Field(default=None)
    """
    **⚠️ DEPRECATED** — Use `extensions.chunking.chunkTypes` instead. Comma-separated list of chunking strategies to apply (for example `semantic,header,page,recursive`). Still accepted for backward compatibility.
    """

    chunk_size: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="chunkSize"),
        pydantic.Field(
            alias="chunkSize",
            description="**⚠️ DEPRECATED** — Use `extensions.chunking.chunkSize` instead. Override for maximum characters per chunk when chunking is enabled.",
        ),
    ] = None
    extract_figure: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="extractFigure"),
        pydantic.Field(
            alias="extractFigure", description="**⚠️ DEPRECATED** — Toggle to enable figure extraction in results."
        ),
    ] = None
    figure_description: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="figureDescription"),
        pydantic.Field(
            alias="figureDescription",
            description="**⚠️ DEPRECATED** — Use `figureProcessing.description` instead. Toggle to generate descriptive captions for extracted figures.",
        ),
    ] = None
    show_images: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="showImages"),
        pydantic.Field(
            alias="showImages",
            description="**⚠️ DEPRECATED** — Use `figureProcessing.showImages` instead. Embed base64-encoded images inline in figure tags in the output. Increases response size.",
        ),
    ] = None
    return_html: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="returnHtml"),
        pydantic.Field(
            alias="returnHtml",
            description="**⚠️ DEPRECATED** — Use `extensions.altOutputs.returnHtml` instead. Whether to include HTML representation alongside markdown in the response.",
        ),
    ] = None
    thinking: typing.Optional[bool] = pydantic.Field(default=None)
    """
    (Deprecated) Enables expanded rationale output for debugging.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
