# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ExtractAsyncRequestSpreadsheet(UncheckedBaseModel):
    """
    Settings for Excel/spreadsheet extraction. Controls handling of hidden rows, columns, and sheets, whether numeric cells are rendered using their display format or underlying raw value, and optional trimming of empty phantom rows/columns past the last data-bearing cell. Applies to `.xlsx`, `.xlsm`, and `.xls` files. Accepts both camelCase and snake_case field names.
    """

    include_hidden_rows: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="includeHiddenRows"),
        pydantic.Field(alias="includeHiddenRows", description="Include rows that are hidden in the Excel workbook."),
    ] = None
    include_hidden_cols: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="includeHiddenCols"),
        pydantic.Field(alias="includeHiddenCols", description="Include columns that are hidden in the Excel workbook."),
    ] = None
    include_hidden_sheets: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="includeHiddenSheets"),
        pydantic.Field(
            alias="includeHiddenSheets", description="Include sheets that are hidden in the Excel workbook."
        ),
    ] = None
    use_raw_values: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="useRawValues"),
        pydantic.Field(
            alias="useRawValues",
            description="Emit the underlying numeric value for number cells instead of the Excel display-formatted text (e.g. `1201.67` rather than `$1,202` when the cell uses a rounded currency format). Percent-formatted cells and dates keep their display rendering. Does not apply to legacy `.xls` files.",
        ),
    ] = None
    only_data_rows: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="onlyDataRows"),
        pydantic.Field(
            alias="onlyDataRows",
            description="When true, trim trailing empty rows past the last cell carrying a value or formula before parsing. Excel exports from claims systems and ERPs routinely declare a used range with hundreds of thousands of empty-but-styled phantom rows that inflate file size and exhaust parser memory; enabling this strips them out without touching any cell that actually has data. Surviving cells keep their original A1 coordinates so citations that reference a specific cell remain stable. Defaults to false.",
        ),
    ] = None
    only_data_cols: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="onlyDataCols"),
        pydantic.Field(
            alias="onlyDataCols",
            description="When true, trim trailing empty columns past the last cell carrying a value or formula. Same rationale and coordinate-stability guarantee as `onlyDataRows`. Defaults to false.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
