# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class FormDetectMultipartInput(UncheckedBaseModel):
    """
    Multipart `/form/detect` request. Use this variant to upload a
    PDF directly via `file`.
    """

    file: typing.Optional[str] = pydantic.Field(default=None)
    """
    PDF file to upload directly.
    """

    file_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Alternative to `file`: a public or pre-signed URL Pulse will download.
    """

    form_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reference to a previously processed form. Mutually exclusive with `file` / `file_url`.
    """

    page_range: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the operation to a subset of pages, e.g. `"1-3,5"`.
    """

    async_: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="async")] = pydantic.Field(
        default=None
    )
    """
    Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
