# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .form_cell_type import FormCellType
from .form_checkbox_detail import FormCheckboxDetail


class FormCell(UncheckedBaseModel):
    """
    A single detected cell on a form page. Cells are produced by Pulse
    cell detection during a `/form/detect`, `/form/fill`, or
    `/form/clear` call and may be passed back via `form_fields` to
    override what Pulse uses when filling or clearing.

    All coordinate fields (`bounding_box`, `checkbox_coord`) are
    normalized to `[0, 1]` relative to the page width / height, so
    they're independent of the renderer's pixel resolution. Multiply
    by your render width / height to convert to your own pixel space.
    `page_number` is 1-indexed.
    """

    page_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    1-indexed page the cell belongs to.
    """

    bounding_box: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Cell bounding box `[x1, y1, x2, y2]` normalized to the range `[0, 1]` (top-left origin). Same shape as the `bounding_box` field returned by `/extract`.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current text content of the cell. Empty string for unfilled cells.
    """

    type: typing.Optional[FormCellType] = pydantic.Field(default=None)
    """
    Detected cell type. Common values are `text`, `checkbox`, and `signature`. Additional values may be returned as the detector evolves.
    """

    row: typing.Optional[int] = pydantic.Field(default=None)
    """
    Row index inside the detected table this cell belongs to, when the cell sits in a tabular region.
    """

    col: typing.Optional[int] = pydantic.Field(default=None)
    """
    Column index inside the detected table this cell belongs to, when the cell sits in a tabular region.
    """

    table_idx: typing.Optional[int] = pydantic.Field(default=None)
    """
    Index of the detected table on the page this cell belongs to (0-indexed). Cells outside any detected table may omit this field.
    """

    checkbox_details: typing.Optional[typing.List[FormCheckboxDetail]] = pydantic.Field(default=None)
    """
    Only present when `type == "checkbox"`. One entry per individual checkbox inside this cell — a single cell often contains multiple checkboxes (e.g. a "Filing Status" row with Single / MFJ / MFS / HoH / QSS). The cell-level `text` is the raw OCR'd line covering the whole cell; per-box labels live here on each detail.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
