# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .form_cell import FormCell


class FormFillJsonInput(UncheckedBaseModel):
    """
    JSON request body for `/form/fill`. Provide exactly one of
    `form_id`, `file_url`, or `file` (multipart only).
    """

    form_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID returned by a previous `/form/detect`, `/form/fill`, or `/form/clear` call. Reuses the stored PDF and cached `form_fields` (fast path; skips re-detection).
    """

    file_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public or pre-signed URL of a PDF to download and fill.
    """

    instructions: str = pydantic.Field()
    """
    Required natural-language description of what to fill into the form (e.g. `"Use John Doe, 123 Main St, born 1990-01-01"`).
    """

    form_fields: typing.Optional[typing.List[FormCell]] = pydantic.Field(default=None)
    """
    Optional override for the cells used when filling / clearing. When omitted, Pulse uses the cells stored on the referenced `form_id` (fast path) or runs detection on the uploaded PDF. Useful for editing detected cells before filling.
    """

    page_range: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the operation to a subset of pages. Accepts comma-separated page numbers and ranges, e.g. `"1-3,5"`. Alias: `pages`.
    """

    async_: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="async"),
        pydantic.Field(
            alias="async",
            description='When `true`, the endpoint returns immediately with `{job_id, status: "pending"}` (HTTP 202) and processes the job in the background. Poll [GET /job/{jobId}](api:GET/job/{jobId}) for the result. Default `false` — return the full result inline.',
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
