# This file was auto-generated by Fern from our API Definition.

from .plan_info import PlanInfo

FormPlanInfo = PlanInfo
"""
**Deprecated** — Use `PlanInfo` instead. Retained as an alias so existing SDK type imports continue to compile.
"""
