# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_options import ExtractOptions
from .pipeline_step_batch_extract_config import PipelineStepBatchExtractConfig
from .schema_config import SchemaConfig
from .split_config import SplitConfig
from .tables_config import TablesConfig


class PipelineSteps(UncheckedBaseModel):
    """
    Ordered step definitions. Key order determines execution order. Use `extract` for single-file or `batch_extract` for multi-file pipelines — they are mutually exclusive. Each step accepts the same configuration as its standalone endpoint.
    """

    extract: typing.Optional[ExtractOptions] = pydantic.Field(default=None)
    """
    Single-document extraction step. Same options as `POST /extract`.
    """

    batch_extract: typing.Optional[PipelineStepBatchExtractConfig] = pydantic.Field(default=None)
    """
    Multi-document parallel extraction step. Provide `file_urls` at the top level and optional `workers` here.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[SchemaConfig],
        FieldMetadata(alias="schema"),
        pydantic.Field(
            alias="schema",
            description="Structured data extraction step. Same config as `schema_config` in `POST /schema`. Requires `extract` or `batch_extract` before it.",
        ),
    ] = None
    split: typing.Optional[SplitConfig] = pydantic.Field(default=None)
    """
    Topic splitting step. Same config as `split_config` in `POST /split`. Requires `extract` or `batch_extract` before it.
    """

    tables: typing.Optional[TablesConfig] = pydantic.Field(default=None)
    """
    Table extraction step. Same config as `tables_config` in `POST /tables`. Requires `extract` before it. This is a terminal step — no further steps can follow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
