# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .batch_file_upload import BatchFileUpload
from .pipeline_step_batch_extract_config_extensions import PipelineStepBatchExtractConfigExtensions
from .pipeline_step_batch_extract_config_figure_processing import PipelineStepBatchExtractConfigFigureProcessing
from .pipeline_step_batch_extract_config_model import PipelineStepBatchExtractConfigModel
from .pipeline_step_batch_extract_config_schema import PipelineStepBatchExtractConfigSchema
from .pipeline_step_batch_extract_config_spreadsheet import PipelineStepBatchExtractConfigSpreadsheet
from .pipeline_step_batch_extract_config_storage import PipelineStepBatchExtractConfigStorage
from .pipeline_step_batch_extract_config_structured_output import PipelineStepBatchExtractConfigStructuredOutput


class PipelineStepBatchExtractConfig(UncheckedBaseModel):
    """
    Configuration for the batch_extract step. Same extract options as `POST /extract` (applied to every file) plus file inputs and a `workers` field for parallelism. Provide files via `file_urls` (URL list) or `files` (base64 inline uploads).
    """

    model: typing.Optional[PipelineStepBatchExtractConfigModel] = pydantic.Field(default=None)
    """
    Extraction model to use. When set to `pulse-ultra-2`, routes the request through Pulse Ultra 2 (self-hosted VPC model) instead of the default cloud-based service. If omitted or set to `default`, the default model is used.
    """

    pages: typing.Optional[str] = pydantic.Field(default=None)
    """
    Page range filter supporting segments such as `1-2` or mixed ranges like `1-2,5`.
    """

    figure_processing: typing_extensions.Annotated[
        typing.Optional[PipelineStepBatchExtractConfigFigureProcessing], FieldMetadata(alias="figureProcessing")
    ] = pydantic.Field(default=None)
    """
    Settings that control how figures in the document are processed. These affect the markdown output directly (e.g. figure descriptions, chart-to-table conversion, image embedding) and do not produce additional output fields in the response.
    """

    extensions: typing.Optional[PipelineStepBatchExtractConfigExtensions] = pydantic.Field(default=None)
    """
    Settings that enable additional processing passes or alternate output formats. Each enabled extension produces a corresponding output field under `response.extensions.*`.
    """

    spreadsheet: typing.Optional[PipelineStepBatchExtractConfigSpreadsheet] = pydantic.Field(default=None)
    """
    Settings for Excel/spreadsheet extraction. Controls handling of hidden rows, columns, and sheets. Only applies to `.xlsx` and `.xls` files. Accepts both camelCase and snake_case field names.
    """

    storage: typing.Optional[PipelineStepBatchExtractConfigStorage] = pydantic.Field(default=None)
    """
    Options for persisting extraction artifacts. When enabled (default), artifacts are saved to storage and a database record is created.
    """

    async_: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="async")] = pydantic.Field(
        default=None
    )
    """
    If true, returns immediately with a job_id for polling via GET /job/{jobId}. Otherwise processes synchronously.
    """

    structured_output: typing_extensions.Annotated[
        typing.Optional[PipelineStepBatchExtractConfigStructuredOutput], FieldMetadata(alias="structuredOutput")
    ] = pydantic.Field(default=None)
    """
    **⚠️ DEPRECATED** — Use the `/schema` endpoint after extraction instead. Pass the `extraction_id` from the extract response to `/schema` with your `schema_config`. This parameter still works for backward compatibility but will be removed in a future version.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[PipelineStepBatchExtractConfigSchema], FieldMetadata(alias="schema")
    ] = pydantic.Field(default=None)
    """
    (Deprecated) JSON schema describing structured data to extract. Use structuredOutput instead. Accepts either a JSON object or a stringified JSON representation.
    """

    schema_prompt: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="schemaPrompt")] = (
        pydantic.Field(default=None)
    )
    """
    (Deprecated) Natural language prompt for schema-guided extraction. Use structuredOutput.schemaPrompt instead.
    """

    custom_prompt: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="customPrompt")] = (
        pydantic.Field(default=None)
    )
    """
    (Deprecated) Custom instructions that augment the default extraction behaviour. Use `figureProcessing` or `extensions` instead.
    """

    chunking: typing.Optional[str] = pydantic.Field(default=None)
    """
    **⚠️ DEPRECATED** — Use `extensions.chunking.chunkTypes` instead. Comma-separated list of chunking strategies to apply (for example `semantic,header,page,recursive`). Still accepted for backward compatibility.
    """

    chunk_size: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="chunkSize")] = pydantic.Field(
        default=None
    )
    """
    **⚠️ DEPRECATED** — Use `extensions.chunking.chunkSize` instead. Override for maximum characters per chunk when chunking is enabled.
    """

    extract_figure: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="extractFigure")] = (
        pydantic.Field(default=None)
    )
    """
    **⚠️ DEPRECATED** — Toggle to enable figure extraction in results.
    """

    figure_description: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="figureDescription")] = (
        pydantic.Field(default=None)
    )
    """
    **⚠️ DEPRECATED** — Use `figureProcessing.description` instead. Toggle to generate descriptive captions for extracted figures.
    """

    show_images: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="showImages")] = pydantic.Field(
        default=None
    )
    """
    **⚠️ DEPRECATED** — Use `figureProcessing.showImages` instead. Embed base64-encoded images inline in figure tags in the output. Increases response size.
    """

    return_html: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="returnHtml")] = pydantic.Field(
        default=None
    )
    """
    **⚠️ DEPRECATED** — Use `extensions.altOutputs.returnHtml` instead. Whether to include HTML representation alongside markdown in the response.
    """

    thinking: typing.Optional[bool] = pydantic.Field(default=None)
    """
    (Deprecated) Enables expanded rationale output for debugging.
    """

    file_urls: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of document URLs to process in parallel.
    """

    files: typing.Optional[typing.List[BatchFileUpload]] = pydantic.Field(default=None)
    """
    Inline file uploads. Each entry contains a filename and base64-encoded file content. Use instead of `file_urls` when you have local files.
    """

    workers: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of parallel workers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
