# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class PipelineExecuteMultipartInput(UncheckedBaseModel):
    """
    Multipart form-data request body for ad-hoc pipeline execution. Upload file(s) directly and provide step configs as a JSON string.
    """

    file: typing.Optional[bytes] = pydantic.Field(default=None)
    """
    Document file to upload. For batch_extract, multiple `file` fields can be provided.
    """

    steps: str = pydantic.Field()
    """
    JSON string containing the step configurations (same structure as `PipelineSteps`).
    """

    async_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="async"),
        pydantic.Field(alias="async", description='Set to `"true"` for async execution.'),
    ] = None
    auto_delete: typing.Optional[str] = pydantic.Field(default=None)
    """
    Set to `"true"` for zero-retention mode.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
