# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SchemaConfig(UncheckedBaseModel):
    """
    Inline schema configuration.
    """

    input_schema: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    JSON Schema defining the structured data to extract.
    """

    schema_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Natural language prompt with additional extraction instructions.
    """

    effort: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable extended reasoning for complex extractions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
