# This file was auto-generated by Fern from our API Definition.

import typing

from .single_schema_response import SingleSchemaResponse
from .split_schema_response import SplitSchemaResponse

SchemaResponse = typing.Union[SingleSchemaResponse, SplitSchemaResponse]
