# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .structured_output_result import StructuredOutputResult


class SingleSchemaResponse(UncheckedBaseModel):
    """
    Response for single schema extraction mode.
    """

    schema_id: str = pydantic.Field()
    """
    Unique identifier for this schema version.
    """

    version: int = pydantic.Field()
    """
    Version number of this schema for the extraction.
    """

    schema_output: StructuredOutputResult = pydantic.Field()
    """
    Extracted values and citations.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
