# This file was auto-generated by Fern from our API Definition.

from .split_result_core import SplitResultCore

SplitResponse = SplitResultCore
"""
Result of document splitting with page assignments.
"""
