# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .topic_definition import TopicDefinition


class SplitConfig(UncheckedBaseModel):
    """
    Inline split configuration with topic definitions.
    """

    split_input: typing.List[TopicDefinition] = pydantic.Field()
    """
    List of topics to identify in the document. Each topic will be assigned page numbers where relevant content is found.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
