# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SplitOutput(UncheckedBaseModel):
    """
    Page assignments per topic. Each key is a topic name and the value is an array of 1-indexed page numbers.
    """

    splits: typing.Optional[typing.Dict[str, typing.List[int]]] = pydantic.Field(default=None)
    """
    Mapping of topic names to arrays of page numbers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
