# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .split_output import SplitOutput


class SplitResponse(UncheckedBaseModel):
    """
    Result of document splitting with page assignments.
    """

    split_id: str = pydantic.Field()
    """
    Unique identifier for this split result. Use this ID with the `/schema` endpoint (split mode) to apply schemas to specific page groups.
    """

    split_output: SplitOutput = pydantic.Field()
    """
    Page assignments per topic.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
