# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class StructuredOutputConfig(UncheckedBaseModel):
    """
    Configuration for schema-guided extraction.
    """

    schema_: typing_extensions.Annotated[typing.Dict[str, typing.Any], FieldMetadata(alias="schema")] = pydantic.Field()
    """
    JSON Schema defining the structured data to extract.
    """

    schema_prompt: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="schemaPrompt")] = (
        pydantic.Field(default=None)
    )
    """
    Natural language instructions for extraction.
    """

    effort: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Use higher quality model for better results. When true, uses a more capable model at the cost of higher latency.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
