# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TablesResponseTablesOutputTablesItem(UncheckedBaseModel):
    table_content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The table content in the requested format (e.g. HTML).
    """

    citations: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Bounding box table IDs indicating where this table was found (e.g. "tbl-1"). Merged tables list all source IDs.
    """

    from_chart: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this table was extracted from a chart or figure rather than a native table.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
