# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .tables_config_table_format import TablesConfigTableFormat


class TablesConfig(UncheckedBaseModel):
    """
    Configuration for table extraction.
    """

    merge: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, adjacent tables that appear to be continuations of each other are merged into a single table.
    """

    table_format: typing.Optional[TablesConfigTableFormat] = pydantic.Field(default=None)
    """
    Output format for table content. `html` returns an HTML `<table>` string. `json` returns a structured object with `headers` (array of column names) and `rows` (array of objects keyed by header name).
    """

    charts_to_tables: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Convert figures and charts into tables using LLM processing. Resulting tables have `from_chart: true` in the response.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
