# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class TopicSchemaConfig(UncheckedBaseModel):
    """
    Per-topic schema configuration.
    Provide EITHER inline schema fields OR schema_config_id reference.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]], FieldMetadata(alias="schema")
    ] = pydantic.Field(default=None)
    """
    JSON Schema for this topic.
    """

    schema_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional instructions for this topic.
    """

    effort: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable extended reasoning.
    """

    schema_config_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reference to a saved schema configuration for this topic.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
