# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.batch_extract_response import BatchExtractResponse
from ..types.batch_input_source import BatchInputSource
from ..types.batch_output_destination import BatchOutputDestination
from ..types.batch_schema_response import BatchSchemaResponse
from ..types.batch_split_response import BatchSplitResponse
from ..types.batch_tables_response import BatchTablesResponse
from ..types.schema_config import SchemaConfig
from ..types.split_config import SplitConfig
from ..types.tables_config import TablesConfig
from ..types.topic_schema_config import TopicSchemaConfig

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawBatchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def extract(
        self,
        *,
        input: BatchInputSource,
        output: BatchOutputDestination,
        extract_options: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchExtractResponse]:
        """
        Process multiple files in parallel. Enumerates files from an input
        source (S3 prefix, local directory, or URL list), calls
        [Extract](api:POST/extract) for each file, and saves results to an
        output destination.

        Always asynchronous — returns a batch job ID immediately.
        Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time progress
        including per-file completion status.

        See the [Extract](api:POST/extract) endpoint for details on
        `extract_options` and the [Batch Processing guide](/batch) for
        an overview of the batch pipeline.

        Parameters
        ----------
        input : BatchInputSource
            Source of files to process.

        output : BatchOutputDestination
            Where to save extraction result JSON files.

        extract_options : typing.Optional[typing.Dict[str, typing.Any]]
            Options forwarded to each `/extract` call (e.g. `pages`, `figureProcessing`, `extensions`).

        workers : typing.Optional[int]
            Number of parallel workers. Higher values increase throughput but consume more server resources.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchExtractResponse]
            Batch extraction started
        """
        _response = self._client_wrapper.httpx_client.request(
            "batch/extract",
            method="POST",
            json={
                "input": convert_and_respect_annotation_metadata(
                    object_=input, annotation=BatchInputSource, direction="write"
                ),
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "extract_options": extract_options,
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchExtractResponse,
                    construct_type(
                        type_=BatchExtractResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def schema(
        self,
        *,
        output: BatchOutputDestination,
        batch_extract_id: typing.Optional[str] = OMIT,
        extraction_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        batch_split_id: typing.Optional[str] = OMIT,
        split_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        schema_config: typing.Optional[SchemaConfig] = OMIT,
        split_schema_config: typing.Optional[typing.Dict[str, TopicSchemaConfig]] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchSchemaResponse]:
        """
        Apply schema extraction to multiple items in parallel.
        Mode is inferred from the input:

        **Single mode** — Provide `extraction_ids` or `batch_extract_id`
        with `schema_config` to apply one schema to each extraction.

        **Split mode** — Provide `split_ids` or `batch_split_id`
        with `split_schema_config` to apply per-topic schemas to each split.

        Each child call goes through the full [Schema](api:POST/schema) code
        path. Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time
        progress.

        See the [Schema](api:POST/schema) endpoint for details on
        `schema_config` and `split_schema_config`, and the
        [Batch Processing guide](/batch) for an overview of the batch
        pipeline.

        Parameters
        ----------
        output : BatchOutputDestination
            Where to save schema result JSON files.

        batch_extract_id : typing.Optional[str]
            ID of a prior `/batch/extract` run (single mode).

        extraction_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of extraction IDs (single mode).

        batch_split_id : typing.Optional[str]
            ID of a prior `/batch/split` run (split mode).

        split_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of split IDs (split mode).

        schema_config : typing.Optional[SchemaConfig]
            Schema configuration for single mode. Applied to each extraction.

        split_schema_config : typing.Optional[typing.Dict[str, TopicSchemaConfig]]
            Per-topic schema configurations for split mode. Keys must match the topic names from the splits.

        page_range : typing.Optional[str]
            Page range filter for single mode (e.g. `1-5,10`).

        workers : typing.Optional[int]
            Number of parallel workers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchSchemaResponse]
            Batch schema started
        """
        _response = self._client_wrapper.httpx_client.request(
            "batch/schema",
            method="POST",
            json={
                "batch_extract_id": batch_extract_id,
                "extraction_ids": extraction_ids,
                "batch_split_id": batch_split_id,
                "split_ids": split_ids,
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "schema_config": convert_and_respect_annotation_metadata(
                    object_=schema_config, annotation=SchemaConfig, direction="write"
                ),
                "split_schema_config": convert_and_respect_annotation_metadata(
                    object_=split_schema_config, annotation=typing.Dict[str, TopicSchemaConfig], direction="write"
                ),
                "page_range": page_range,
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchSchemaResponse,
                    construct_type(
                        type_=BatchSchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def tables(
        self,
        *,
        output: BatchOutputDestination,
        batch_extract_id: typing.Optional[str] = OMIT,
        extraction_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tables_config: typing.Optional[TablesConfig] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchTablesResponse]:
        """
        Extract tables from multiple existing extractions in parallel.
        Each child call goes through the full [Tables](api:POST/tables) code
        path.

        Extractions are identified by either a `batch_extract_id` (from a
        prior [Batch Extract](api:POST/batch/extract) run) or an explicit
        list of `extraction_ids`.

        Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time progress.

        See the [Tables](api:POST/tables) endpoint for details on
        `tables_config` and the [Batch Processing guide](/batch) for an
        overview of the batch pipeline.

        Parameters
        ----------
        output : BatchOutputDestination
            Where to save table result JSON files.

        batch_extract_id : typing.Optional[str]
            ID of a prior `/batch/extract` run. All completed child extraction IDs will be used.

        extraction_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of extraction IDs to process.

        tables_config : typing.Optional[TablesConfig]
            Table extraction configuration forwarded to each `/tables` call.

        workers : typing.Optional[int]
            Number of parallel workers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchTablesResponse]
            Batch tables started
        """
        _response = self._client_wrapper.httpx_client.request(
            "batch/tables",
            method="POST",
            json={
                "batch_extract_id": batch_extract_id,
                "extraction_ids": extraction_ids,
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "tables_config": convert_and_respect_annotation_metadata(
                    object_=tables_config, annotation=TablesConfig, direction="write"
                ),
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchTablesResponse,
                    construct_type(
                        type_=BatchTablesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def split(
        self,
        *,
        output: BatchOutputDestination,
        split_config: SplitConfig,
        batch_extract_id: typing.Optional[str] = OMIT,
        extraction_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchSplitResponse]:
        """
        Split multiple existing extractions by topics in parallel.
        Each child call goes through the full [Split](api:POST/split) code
        path.

        Extractions are identified by either a `batch_extract_id` (from a
        prior [Batch Extract](api:POST/batch/extract) run) or an explicit
        list of `extraction_ids`.

        Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time progress.

        See the [Split](api:POST/split) endpoint for details on
        `split_config` and the [Batch Processing guide](/batch) for an
        overview of the batch pipeline.

        Parameters
        ----------
        output : BatchOutputDestination
            Where to save split result JSON files.

        split_config : SplitConfig
            Split configuration with topic definitions. Applied to each extraction.

        batch_extract_id : typing.Optional[str]
            ID of a prior `/batch/extract` run. All completed child extraction IDs will be used.

        extraction_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of extraction IDs to process.

        workers : typing.Optional[int]
            Number of parallel workers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchSplitResponse]
            Batch split started
        """
        _response = self._client_wrapper.httpx_client.request(
            "batch/split",
            method="POST",
            json={
                "batch_extract_id": batch_extract_id,
                "extraction_ids": extraction_ids,
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "split_config": convert_and_respect_annotation_metadata(
                    object_=split_config, annotation=SplitConfig, direction="write"
                ),
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchSplitResponse,
                    construct_type(
                        type_=BatchSplitResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawBatchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def extract(
        self,
        *,
        input: BatchInputSource,
        output: BatchOutputDestination,
        extract_options: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchExtractResponse]:
        """
        Process multiple files in parallel. Enumerates files from an input
        source (S3 prefix, local directory, or URL list), calls
        [Extract](api:POST/extract) for each file, and saves results to an
        output destination.

        Always asynchronous — returns a batch job ID immediately.
        Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time progress
        including per-file completion status.

        See the [Extract](api:POST/extract) endpoint for details on
        `extract_options` and the [Batch Processing guide](/batch) for
        an overview of the batch pipeline.

        Parameters
        ----------
        input : BatchInputSource
            Source of files to process.

        output : BatchOutputDestination
            Where to save extraction result JSON files.

        extract_options : typing.Optional[typing.Dict[str, typing.Any]]
            Options forwarded to each `/extract` call (e.g. `pages`, `figureProcessing`, `extensions`).

        workers : typing.Optional[int]
            Number of parallel workers. Higher values increase throughput but consume more server resources.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchExtractResponse]
            Batch extraction started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "batch/extract",
            method="POST",
            json={
                "input": convert_and_respect_annotation_metadata(
                    object_=input, annotation=BatchInputSource, direction="write"
                ),
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "extract_options": extract_options,
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchExtractResponse,
                    construct_type(
                        type_=BatchExtractResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def schema(
        self,
        *,
        output: BatchOutputDestination,
        batch_extract_id: typing.Optional[str] = OMIT,
        extraction_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        batch_split_id: typing.Optional[str] = OMIT,
        split_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        schema_config: typing.Optional[SchemaConfig] = OMIT,
        split_schema_config: typing.Optional[typing.Dict[str, TopicSchemaConfig]] = OMIT,
        page_range: typing.Optional[str] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchSchemaResponse]:
        """
        Apply schema extraction to multiple items in parallel.
        Mode is inferred from the input:

        **Single mode** — Provide `extraction_ids` or `batch_extract_id`
        with `schema_config` to apply one schema to each extraction.

        **Split mode** — Provide `split_ids` or `batch_split_id`
        with `split_schema_config` to apply per-topic schemas to each split.

        Each child call goes through the full [Schema](api:POST/schema) code
        path. Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time
        progress.

        See the [Schema](api:POST/schema) endpoint for details on
        `schema_config` and `split_schema_config`, and the
        [Batch Processing guide](/batch) for an overview of the batch
        pipeline.

        Parameters
        ----------
        output : BatchOutputDestination
            Where to save schema result JSON files.

        batch_extract_id : typing.Optional[str]
            ID of a prior `/batch/extract` run (single mode).

        extraction_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of extraction IDs (single mode).

        batch_split_id : typing.Optional[str]
            ID of a prior `/batch/split` run (split mode).

        split_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of split IDs (split mode).

        schema_config : typing.Optional[SchemaConfig]
            Schema configuration for single mode. Applied to each extraction.

        split_schema_config : typing.Optional[typing.Dict[str, TopicSchemaConfig]]
            Per-topic schema configurations for split mode. Keys must match the topic names from the splits.

        page_range : typing.Optional[str]
            Page range filter for single mode (e.g. `1-5,10`).

        workers : typing.Optional[int]
            Number of parallel workers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchSchemaResponse]
            Batch schema started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "batch/schema",
            method="POST",
            json={
                "batch_extract_id": batch_extract_id,
                "extraction_ids": extraction_ids,
                "batch_split_id": batch_split_id,
                "split_ids": split_ids,
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "schema_config": convert_and_respect_annotation_metadata(
                    object_=schema_config, annotation=SchemaConfig, direction="write"
                ),
                "split_schema_config": convert_and_respect_annotation_metadata(
                    object_=split_schema_config, annotation=typing.Dict[str, TopicSchemaConfig], direction="write"
                ),
                "page_range": page_range,
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchSchemaResponse,
                    construct_type(
                        type_=BatchSchemaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def tables(
        self,
        *,
        output: BatchOutputDestination,
        batch_extract_id: typing.Optional[str] = OMIT,
        extraction_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        tables_config: typing.Optional[TablesConfig] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchTablesResponse]:
        """
        Extract tables from multiple existing extractions in parallel.
        Each child call goes through the full [Tables](api:POST/tables) code
        path.

        Extractions are identified by either a `batch_extract_id` (from a
        prior [Batch Extract](api:POST/batch/extract) run) or an explicit
        list of `extraction_ids`.

        Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time progress.

        See the [Tables](api:POST/tables) endpoint for details on
        `tables_config` and the [Batch Processing guide](/batch) for an
        overview of the batch pipeline.

        Parameters
        ----------
        output : BatchOutputDestination
            Where to save table result JSON files.

        batch_extract_id : typing.Optional[str]
            ID of a prior `/batch/extract` run. All completed child extraction IDs will be used.

        extraction_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of extraction IDs to process.

        tables_config : typing.Optional[TablesConfig]
            Table extraction configuration forwarded to each `/tables` call.

        workers : typing.Optional[int]
            Number of parallel workers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchTablesResponse]
            Batch tables started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "batch/tables",
            method="POST",
            json={
                "batch_extract_id": batch_extract_id,
                "extraction_ids": extraction_ids,
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "tables_config": convert_and_respect_annotation_metadata(
                    object_=tables_config, annotation=TablesConfig, direction="write"
                ),
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchTablesResponse,
                    construct_type(
                        type_=BatchTablesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def split(
        self,
        *,
        output: BatchOutputDestination,
        split_config: SplitConfig,
        batch_extract_id: typing.Optional[str] = OMIT,
        extraction_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        workers: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchSplitResponse]:
        """
        Split multiple existing extractions by topics in parallel.
        Each child call goes through the full [Split](api:POST/split) code
        path.

        Extractions are identified by either a `batch_extract_id` (from a
        prior [Batch Extract](api:POST/batch/extract) run) or an explicit
        list of `extraction_ids`.

        Poll [GET /job/{jobId}](api:GET/job/{jobId}) for real-time progress.

        See the [Split](api:POST/split) endpoint for details on
        `split_config` and the [Batch Processing guide](/batch) for an
        overview of the batch pipeline.

        Parameters
        ----------
        output : BatchOutputDestination
            Where to save split result JSON files.

        split_config : SplitConfig
            Split configuration with topic definitions. Applied to each extraction.

        batch_extract_id : typing.Optional[str]
            ID of a prior `/batch/extract` run. All completed child extraction IDs will be used.

        extraction_ids : typing.Optional[typing.Sequence[str]]
            Explicit list of extraction IDs to process.

        workers : typing.Optional[int]
            Number of parallel workers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchSplitResponse]
            Batch split started
        """
        _response = await self._client_wrapper.httpx_client.request(
            "batch/split",
            method="POST",
            json={
                "batch_extract_id": batch_extract_id,
                "extraction_ids": extraction_ids,
                "output": convert_and_respect_annotation_metadata(
                    object_=output, annotation=BatchOutputDestination, direction="write"
                ),
                "split_config": convert_and_respect_annotation_metadata(
                    object_=split_config, annotation=SplitConfig, direction="write"
                ),
                "workers": workers,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchSplitResponse,
                    construct_type(
                        type_=BatchSplitResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
