# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.pipeline_execute_response import PipelineExecuteResponse
from ..types.pipeline_steps import PipelineSteps
from .raw_client import AsyncRawPipelineClient, RawPipelineClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PipelineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPipelineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPipelineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPipelineClient
        """
        return self._raw_client

    def execute(
        self,
        *,
        steps: PipelineSteps,
        file_url: typing.Optional[str] = OMIT,
        async_: typing.Optional[bool] = OMIT,
        auto_delete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineExecuteResponse:
        """
        Chain multiple processing steps (extract, schema, split) into a single
        request with inline configurations. No saved pipeline required.

        The `steps` object defines what to run and in what order. Outputs flow
        forward automatically — you never need to pass extraction IDs between
        steps.

        **Supported step combinations:**
        - `extract` — extract a single document
        - `extract` → `schema` — extract then apply structured schema
        - `extract` → `split` — extract then split into topics
        - `batch_extract` → `schema` — extract multiple files, combine into one schema output

        **Document input:**
        - Single file: provide `fileUrl` in JSON or `file` via multipart
        - Multiple files (batch_extract): provide `fileUrls` in JSON or multiple `file` fields via multipart

        Set `async: true` to return immediately with a `job_id` for polling via
        `GET /job/{jobId}`.

        Set `autoDelete: true` for zero-retention mode — all stored artifacts
        are deleted immediately after you receive the results. Requires
        `save_extractions` to be disabled for your organization.

        Requires the `enable_adhoc_pipeline` feature flag.

        Parameters
        ----------
        steps : PipelineSteps
            Ordered step definitions. Key order determines execution order.

        file_url : typing.Optional[str]
            URL of the document to process. Use with `extract` step.

        async_ : typing.Optional[bool]
            If true, returns immediately with a `job_id` for polling via `GET /job/{jobId}`.

        auto_delete : typing.Optional[bool]
            If true, all stored artifacts are deleted immediately after you receive the results. The inline data in the response is unaffected. Requires `save_extractions` to be disabled for your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineExecuteResponse
            Pipeline completed synchronously. Contains results for each step.

        Examples
        --------
        from pulse import PipelineSteps, Pulse

        client = Pulse(
            api_key="YOUR_API_KEY",
        )
        client.pipeline.execute(
            steps=PipelineSteps(),
        )
        """
        _response = self._raw_client.execute(
            steps=steps, file_url=file_url, async_=async_, auto_delete=auto_delete, request_options=request_options
        )
        return _response.data


class AsyncPipelineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPipelineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPipelineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPipelineClient
        """
        return self._raw_client

    async def execute(
        self,
        *,
        steps: PipelineSteps,
        file_url: typing.Optional[str] = OMIT,
        async_: typing.Optional[bool] = OMIT,
        auto_delete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineExecuteResponse:
        """
        Chain multiple processing steps (extract, schema, split) into a single
        request with inline configurations. No saved pipeline required.

        The `steps` object defines what to run and in what order. Outputs flow
        forward automatically — you never need to pass extraction IDs between
        steps.

        **Supported step combinations:**
        - `extract` — extract a single document
        - `extract` → `schema` — extract then apply structured schema
        - `extract` → `split` — extract then split into topics
        - `batch_extract` → `schema` — extract multiple files, combine into one schema output

        **Document input:**
        - Single file: provide `fileUrl` in JSON or `file` via multipart
        - Multiple files (batch_extract): provide `fileUrls` in JSON or multiple `file` fields via multipart

        Set `async: true` to return immediately with a `job_id` for polling via
        `GET /job/{jobId}`.

        Set `autoDelete: true` for zero-retention mode — all stored artifacts
        are deleted immediately after you receive the results. Requires
        `save_extractions` to be disabled for your organization.

        Requires the `enable_adhoc_pipeline` feature flag.

        Parameters
        ----------
        steps : PipelineSteps
            Ordered step definitions. Key order determines execution order.

        file_url : typing.Optional[str]
            URL of the document to process. Use with `extract` step.

        async_ : typing.Optional[bool]
            If true, returns immediately with a `job_id` for polling via `GET /job/{jobId}`.

        auto_delete : typing.Optional[bool]
            If true, all stored artifacts are deleted immediately after you receive the results. The inline data in the response is unaffected. Requires `save_extractions` to be disabled for your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineExecuteResponse
            Pipeline completed synchronously. Contains results for each step.

        Examples
        --------
        import asyncio

        from pulse import AsyncPulse, PipelineSteps

        client = AsyncPulse(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.pipeline.execute(
                steps=PipelineSteps(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.execute(
            steps=steps, file_url=file_url, async_=async_, auto_delete=auto_delete, request_options=request_options
        )
        return _response.data
