# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.pipeline_execute_response import PipelineExecuteResponse
from ..types.pipeline_steps import PipelineSteps
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPipelineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def execute(
        self,
        *,
        steps: PipelineSteps,
        file_url: typing.Optional[str] = OMIT,
        async_: typing.Optional[bool] = OMIT,
        auto_delete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PipelineExecuteResponse]:
        """
        Chain multiple processing steps (extract, schema, split, tables) into a
        single request with inline configurations. No saved pipeline required.

        The `steps` object defines what to run and in what order. Outputs flow
        forward automatically — you never need to pass extraction IDs between
        steps.

        **Supported step combinations:**
        - `extract` — extract a single document
        - `extract` → `schema` — extract then apply structured schema
        - `extract` → `split` — extract then split into topics
        - `extract` → `split` → `schema` — extract, split by topic, apply per-topic schemas
        - `extract` → `tables` — extract then extract structured tables
        - `batch_extract` → `schema` — extract multiple files, combine into one schema output

        **Document input:**
        - Single file: provide `fileUrl` in JSON or `file` via multipart
        - Multiple files (batch_extract): provide `fileUrls` in JSON or multiple `file` fields via multipart

        Set `async: true` to return immediately with a `job_id` for polling via
        `GET /job/{jobId}`.

        Set `autoDelete: true` for zero-retention mode — all stored artifacts
        are deleted immediately after you receive the results. Requires
        `save_extractions` to be disabled for your organization.

        Requires the `enable_adhoc_pipeline` feature flag.

        Parameters
        ----------
        steps : PipelineSteps
            Ordered step definitions. Key order determines execution order.

        file_url : typing.Optional[str]
            URL of the document to process. Use with `extract` step.

        async_ : typing.Optional[bool]
            If true, returns immediately with a `job_id` for polling via `GET /job/{jobId}`.

        auto_delete : typing.Optional[bool]
            If true, all stored artifacts are deleted immediately after you receive the results. The inline data in the response is unaffected. Requires `save_extractions` to be disabled for your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PipelineExecuteResponse]
            Pipeline completed synchronously. Contains results for each step.
        """
        _response = self._client_wrapper.httpx_client.request(
            "pipeline/execute",
            method="POST",
            json={
                "file_url": file_url,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=PipelineSteps, direction="write"
                ),
                "async": async_,
                "auto_delete": auto_delete,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineExecuteResponse,
                    construct_type(
                        type_=PipelineExecuteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPipelineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def execute(
        self,
        *,
        steps: PipelineSteps,
        file_url: typing.Optional[str] = OMIT,
        async_: typing.Optional[bool] = OMIT,
        auto_delete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PipelineExecuteResponse]:
        """
        Chain multiple processing steps (extract, schema, split, tables) into a
        single request with inline configurations. No saved pipeline required.

        The `steps` object defines what to run and in what order. Outputs flow
        forward automatically — you never need to pass extraction IDs between
        steps.

        **Supported step combinations:**
        - `extract` — extract a single document
        - `extract` → `schema` — extract then apply structured schema
        - `extract` → `split` — extract then split into topics
        - `extract` → `split` → `schema` — extract, split by topic, apply per-topic schemas
        - `extract` → `tables` — extract then extract structured tables
        - `batch_extract` → `schema` — extract multiple files, combine into one schema output

        **Document input:**
        - Single file: provide `fileUrl` in JSON or `file` via multipart
        - Multiple files (batch_extract): provide `fileUrls` in JSON or multiple `file` fields via multipart

        Set `async: true` to return immediately with a `job_id` for polling via
        `GET /job/{jobId}`.

        Set `autoDelete: true` for zero-retention mode — all stored artifacts
        are deleted immediately after you receive the results. Requires
        `save_extractions` to be disabled for your organization.

        Requires the `enable_adhoc_pipeline` feature flag.

        Parameters
        ----------
        steps : PipelineSteps
            Ordered step definitions. Key order determines execution order.

        file_url : typing.Optional[str]
            URL of the document to process. Use with `extract` step.

        async_ : typing.Optional[bool]
            If true, returns immediately with a `job_id` for polling via `GET /job/{jobId}`.

        auto_delete : typing.Optional[bool]
            If true, all stored artifacts are deleted immediately after you receive the results. The inline data in the response is unaffected. Requires `save_extractions` to be disabled for your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PipelineExecuteResponse]
            Pipeline completed synchronously. Contains results for each step.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "pipeline/execute",
            method="POST",
            json={
                "file_url": file_url,
                "steps": convert_and_respect_annotation_metadata(
                    object_=steps, annotation=PipelineSteps, direction="write"
                ),
                "async": async_,
                "auto_delete": auto_delete,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineExecuteResponse,
                    construct_type(
                        type_=PipelineExecuteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
